version: "3.9"
services:
  magic-app-prod:
    image: magic-app:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
